# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    container_name: mysql_test
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: test
      MYSQL_USER: golkhandani
      MYSQL_PASSWORD: mrzg6794
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_test
    links:
      - db
    environment:
      PMA_HOST: mysql_test
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8183:80

volumes:
  my-db: